// ============================================================
// RevLinkXmlGenerator.cs —— 生成"业务侧"的 IL2CPP 裁剪保护文件（link.xml）
//
// 位置：Editor\RevPlatform\
//
// 【★ 先说前提：本框架的主推方案是"把代码裁剪关掉"】
//   见 Revolution.Document/代码裁剪/代码裁剪使用说明.md（讲清了代价怎么自己测、被裁了会是什么症状）。
//   本工具是【万一你确实要开裁剪】时的护栏：把"被裁"从"真机上的神秘故障"变成"出包时看得见的清单"。
//
// 【为什么需要它】
//   框架的 UI 是靠**反射**装配的：
//     · [RevBind] 字段       → FieldInfo.SetValue 写入
//     · [RevUIPanel] / [RevUIPart] 特性 → GetCustomAttributes 读取
//     · [RevUIxxx] 事件方法   → GetMethods 扫描 + MethodInfo.Invoke 调用
//   单例又靠反射构造（GetConstructor + Invoke）。
//   这些成员在编译器眼里"没人用" —— 只要 Managed Stripping Level 调到 Medium 以上，它们就会被裁掉。
//   症状极隐蔽：**编辑器里一切正常，真机上面板空白、按钮点不动、单例建不出来**。
//
//   ★ 框架只能在自己那份 link.xml 里保住框架类型与 UnityEngine 类型，保不了业务类型。
//     而手写业务 link.xml 要穷举所有面板类，改个名字就漏 —— 且漏了不报错，只在真机上炸。
//     所以这里做成"一键扫描生成"。
//
// 【生成到哪】
//   Assets/link.xml（工程根，不进框架目录、不会被 UPM 包更新覆盖）。
//   Unity 会自动合并读取工程内**所有** link.xml，所以它与框架自带的那份是叠加关系。
//
// 【什么时候重新生成】
//   新增 / 改名 / 删除任何 RevUIPanel / RevUIPart / RevSingleton 派生类之后。
//   生成文件是覆盖式的（带生成标记），不要手改。
// ============================================================
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Revolution.Editor
{
    internal static class RevLinkXmlGenerator
    {
        /// <summary>生成位置：工程根 Assets 下（不放进框架目录，避免被包更新覆盖）。</summary>
        private const string OutputPath = "Assets/link.xml";

        /// <summary>
        /// 生成文件里的标记。用它区分"本工具生成的"（可直接覆盖）和"业务手写的"（必须先确认）——
        /// 绝不静默覆盖别人手写的东西。
        /// </summary>
        private const string GeneratedMark = "Generated by Revolution";

        [MenuItem("Revolution.Tools/平台/生成 IL2CPP 裁剪保护 (link.xml)", false, 40)]
        public static void Generate()
        {
            List<Type> types = CollectBusinessTypes();
            List<string> nativeModules = ScanNativeModules();      // 物理 / UI / 动画… 这些原生模块同样会被裁

            if (types.Count == 0 && nativeModules.Count == 0)
            {
                RevABLog.Warn("[LinkXml] 没扫到任何需要保护的内容：既没有 RevUIPanel / RevUIPart / RevSingleton 派生类，" +
                              "代码里也没用到 Unity 原生模块。如果工程里还没有业务面板与单例，这个文件暂时不需要生成。");
                return;
            }

            if (!ConfirmOverwrite()) { return; }

            File.WriteAllText(OutputPath, BuildXml(types, nativeModules), new UTF8Encoding(false));
            AssetDatabase.ImportAsset(OutputPath);
            AssetDatabase.Refresh();

            RevABLog.Info($"[LinkXml] 已生成裁剪保护：反射类型 {types.Count} 个 / 原生模块 {nativeModules.Count} 个 → {OutputPath}\n" +
                          "  · 新增 / 改名面板或单例后请重新执行本菜单；\n" +
                          "  · 换 Unity 版本、加了新原生模块、改了出包配置之后，也建议重跑一次，\n" +
                          "    并在真机上主动跑一次 RevStripGuard.Check() 确认关键类型还在（比等玩法瘫了再查快得多）。");
        }

        // ============================================================
        // 收集：哪些业务类型是靠反射使用的
        // ============================================================

        private static List<Type> CollectBusinessTypes()
        {
            var result = new List<Type>();
            var seen = new HashSet<Type>();

            // ① UI：面板与 Part —— [RevBind] 字段、面板特性、事件方法都长在这些类型上
            foreach (Type type in TypeCache.GetTypesDerivedFrom<RevUIPanel>()) { AddIfUsable(type, result, seen); }
            foreach (Type type in TypeCache.GetTypesDerivedFrom<RevUIPart>()) { AddIfUsable(type, result, seen); }

            // ② 单例：基类是泛型（RevSingleton<T> 等），TypeCache 查不了泛型，只能遍历程序集自己判
            foreach (Type type in EnumerateBusinessAssemblyTypes())
            {
                if (IsSingletonDerived(type)) { AddIfUsable(type, result, seen); }
            }

            // 排序：让生成文件稳定可复现（同样的代码永远生成同样的文件，diff 才看得清改了什么）
            result.Sort((a, b) => string.CompareOrdinal(a.FullName, b.FullName));
            return result;
        }

        /// <summary>
        /// 遍历"业务程序集"里的所有类型。
        /// ★ 跳过框架与系统程序集：框架类型已由框架自带 link.xml 保护；系统程序集不归业务管。
        /// </summary>
        private static IEnumerable<Type> EnumerateBusinessAssemblyTypes()
        {
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (!IsBusinessAssembly(assembly.GetName().Name)) { continue; }

                Type[] types;
                try
                {
                    types = assembly.GetTypes();
                }
                catch (ReflectionTypeLoadException e)
                {
                    // 有类型加载失败时不要把整次扫描废掉：能拿到的那部分照样保护（拿不到的本来也编译不进包）
                    types = e.Types;
                }

                foreach (Type type in types)
                {
                    if (type != null) { yield return type; }
                }
            }
        }

        private static bool IsBusinessAssembly(string name)
        {
            if (string.IsNullOrEmpty(name)) { return false; }

            // 框架自己的（Revolution / Revolution.HotUpdate / Revolution.Generation / Revolution.Editor）
            if (name.StartsWith("Revolution", StringComparison.Ordinal)) { return false; }

            // 系统 / 引擎 / 第三方基础库：这些不该出现在业务的 link.xml 里
            if (name.StartsWith("System", StringComparison.Ordinal)) { return false; }
            if (name.StartsWith("Unity", StringComparison.Ordinal)) { return false; }
            if (name.StartsWith("Microsoft", StringComparison.Ordinal)) { return false; }
            if (name.StartsWith("Mono", StringComparison.Ordinal)) { return false; }
            if (name.StartsWith("netstandard", StringComparison.Ordinal)) { return false; }
            if (name.StartsWith("mscorlib", StringComparison.Ordinal)) { return false; }
            if (name.StartsWith("nunit", StringComparison.Ordinal)) { return false; }
            if (name.StartsWith("JetBrains", StringComparison.Ordinal)) { return false; }
            return true;
        }

        /// <summary>基类链上有没有 RevSingleton&lt;T&gt; / RevSingletonMono&lt;T&gt; / RevSingletonAutoMono&lt;T&gt;。</summary>
        private static bool IsSingletonDerived(Type type)
        {
            for (Type t = type.BaseType; t != null; t = t.BaseType)
            {
                if (!t.IsGenericType) { continue; }

                Type definition = t.GetGenericTypeDefinition();
                if (definition == typeof(RevSingleton<>)
                    || definition == typeof(RevSingletonMono<>)
                    || definition == typeof(RevSingletonAutoMono<>))
                {
                    return true;
                }
            }

            return false;
        }

        private static void AddIfUsable(Type type, List<Type> result, HashSet<Type> seen)
        {
            // 这几种保不了 / 不需要保：
            //   · 抽象类：不会被实例化，真正要保的是它的派生类；
            //   · 泛型定义（如 MyPanel<T>）：link.xml 里要写成 "Type`1"，且真正需要保的是它的**实例**，
            //     这类由框架那份 link.xml 覆盖基类泛型；
            //   · 嵌套类型：反射名要用 '+' 连接，容易写错，直接跳过。
            if (type == null || type.IsAbstract || type.IsGenericTypeDefinition || type.IsNested) { return; }
            if (type.FullName == null) { return; }
            if (!seen.Add(type)) { return; }

            result.Add(type);
        }

        // ============================================================
        // 收集：Unity 原生模块（native binding）—— 代码裁剪的头号坑
        // ============================================================

        /// <summary>
        /// 原生模块探针：代码里出现这个关键字 → 它的托管 wrapper 就该被保留。
        ///
        /// 【★ 为什么不能按"程序集被引用过"来判断】
        ///   只要业务 using 了 UnityEngine，UnityEngine.CoreModule 就在引用列表里 ——
        ///   照那个判会把巨大的 CoreModule 整个 preserve，纯粹撑大包体。
        ///   原生模块真正危险的地方恰恰是"**场景 / Prefab 上挂了组件、代码却没直接 new**"，
        ///   所以只能按"代码里真的用到了这个类名"来补 —— 这是能做到的最准的一版。
        ///
        /// 【覆盖不到的另一半（由框架 link.xml 兜底）】
        ///   "场景里挂了 Rigidbody 但代码从不 new"这类，纯扫代码看不出来。
        ///   框架自带的 Assets/Revolution/link.xml 已固定保了物理 / UI / 动画 / 音频 / 粒子
        ///   这几个几乎必用的原生模块，两者互补。
        /// </summary>
        private static readonly KeyValuePair<string, string>[] NativeModuleMarkers =
        {
            new KeyValuePair<string, string>("Rigidbody", "UnityEngine.PhysicsModule"),
            new KeyValuePair<string, string>("Physics.", "UnityEngine.PhysicsModule"),
            new KeyValuePair<string, string>("Collider", "UnityEngine.PhysicsModule"),
            new KeyValuePair<string, string>("Rigidbody2D", "UnityEngine.Physics2DModule"),
            new KeyValuePair<string, string>("Physics2D", "UnityEngine.Physics2DModule"),
            new KeyValuePair<string, string>("NavMesh", "UnityEngine.AIModule"),
            new KeyValuePair<string, string>("TerrainCollider", "UnityEngine.TerrainPhysicsModule"),
            new KeyValuePair<string, string>("ParticleSystem", "UnityEngine.ParticleSystemModule"),
            new KeyValuePair<string, string>("Animator", "UnityEngine.AnimationModule"),
            new KeyValuePair<string, string>("AnimationClip", "UnityEngine.AnimationModule"),
            new KeyValuePair<string, string>("Canvas", "UnityEngine.UIModule"),
            new KeyValuePair<string, string>("AudioSource", "UnityEngine.AudioModule"),
            new KeyValuePair<string, string>("AudioClip", "UnityEngine.AudioModule"),
            new KeyValuePair<string, string>("VideoPlayer", "UnityEngine.VideoModule"),
            new KeyValuePair<string, string>("VisualEffect", "UnityEngine.VFXModule"),
            new KeyValuePair<string, string>("TextMeshPro", "Unity.TextMeshPro"),
            new KeyValuePair<string, string>("UnityEngine.InputSystem", "Unity.InputSystem"),
        };

        /// <summary>
        /// 扫工程源码，找出"用到了但保不住"的 Unity 原生模块。
        /// ★ 会读一遍 Assets 下所有 .cs（上千个文件时几秒），因此只做这一次、别放进每次编译。
        /// </summary>
        private static List<string> ScanNativeModules()
        {
            var found = new List<string>();
            if (Directory.Exists(Application.dataPath) == false) { return found; }

            // 只保留"本工程真的加载得到"的程序集：link.xml 里写一个不存在的程序集，
            // 轻则一堆警告、重则构建失败（小游戏用的 Input System 不是每个工程都装了）。
            var loaded = new HashSet<string>(StringComparer.Ordinal);
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies()) { loaded.Add(assembly.GetName().Name); }

            string[] files;
            try
            {
                files = Directory.GetFiles(Application.dataPath, "*.cs", SearchOption.AllDirectories);
            }
            catch (Exception e)
            {
                RevABLog.Warn("[LinkXml] 扫描源码失败，原生模块需要手工确认：" + e.Message);
                return found;
            }

            for (int i = 0; i < files.Length; i++)
            {
                string text;
                try { text = File.ReadAllText(files[i]); }
                catch { continue; }               // 读不了的（被占用 / 特殊编码）跳过，不中断整次扫描

                for (int m = 0; m < NativeModuleMarkers.Length; m++)
                {
                    if (loaded.Contains(NativeModuleMarkers[m].Value) == false) { continue; }   // 本工程没有这个模块
                    if (found.Contains(NativeModuleMarkers[m].Value)) { continue; }              // 已经记过了

                    if (text.Contains(NativeModuleMarkers[m].Key)) { found.Add(NativeModuleMarkers[m].Value); }
                }
            }

            found.Sort(StringComparer.Ordinal);
            return found;
        }

        // ============================================================
        // 写文件
        // ============================================================

        /// <summary>
        /// 已存在且**不是**本工具生成的 → 弹窗让用户决定，绝不静默覆盖别人手写的文件。
        /// </summary>
        private static bool ConfirmOverwrite()
        {
            if (!File.Exists(OutputPath)) { return true; }
            if (File.ReadAllText(OutputPath).Contains(GeneratedMark)) { return true; }

            return EditorUtility.DisplayDialog(
                "link.xml 已存在",
                $"{OutputPath} 已经存在，而且看起来不是本工具生成的（没有生成标记）。\n\n" +
                "继续会覆盖它。如果那是你手写的裁剪保护内容，请先备份。",
                "覆盖", "取消");
        }

        private static string BuildXml(List<Type> types, List<string> nativeModules)
        {
            // 按程序集分组：link.xml 的结构就是 assembly → 它下面的 type
            var byAssembly = new SortedDictionary<string, List<Type>>(StringComparer.Ordinal);
            foreach (Type type in types)
            {
                string assemblyName = type.Assembly.GetName().Name;
                if (!byAssembly.TryGetValue(assemblyName, out List<Type> list))
                {
                    list = new List<Type>();
                    byAssembly[assemblyName] = list;
                }

                list.Add(type);
            }

            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine($"<!-- {GeneratedMark}：由菜单「Revolution.Tools/平台/生成 IL2CPP 裁剪保护 (link.xml)」生成，" +
                          $"请勿手改（重新生成会覆盖）。生成时间：{DateTime.Now:yyyy-MM-dd HH:mm:ss} -->");
            sb.AppendLine("<!--");
            sb.AppendLine("  本文件保护两类东西：");
            sb.AppendLine("  ① 靠反射使用的类型：");
            sb.AppendLine("     · UI 面板 / Part 的 [RevBind] 字段与 [RevUIxxx] 事件方法；");
            sb.AppendLine("     · [RevUIPanel] / [RevUIPart] 特性；");
            sb.AppendLine("     · 单例的构造函数（只被反射调用）。");
            sb.AppendLine("     症状：编辑器一切正常、真机上面板空白 / 按钮点不动 / 单例建不出来。");
            sb.AppendLine("  ② Unity 原生模块（native binding，扫代码自动补上）：");
            sb.AppendLine("     物理 / UI / 动画 / 音频 / 粒子这些模块真实现都在引擎原生侧（C++），");
            sb.AppendLine("     托管层只是 wrapper —— 业务没直接调就会被裁掉，而场景里的组件还好好挂着，");
            sb.AppendLine("     于是变成【编辑器正常、真机静默失效】：刚体变空壳、Raycast 恒空、动画不动、没声音。");
            sb.AppendLine("  ★ 新增 / 改名 / 删除面板或单例之后，重新执行一次生成菜单即可。");
            sb.AppendLine("  ★ 框架自带的 Assets/Revolution/link.xml 已固定保住物理 / UI / 动画 / 音频 / 粒子，");
            sb.AppendLine("    两份会被 Unity 合并读取，互为补充。");
            sb.AppendLine("-->");
            sb.AppendLine("<linker>");

            foreach (KeyValuePair<string, List<Type>> pair in byAssembly)
            {
                sb.AppendLine($"  <assembly fullname=\"{pair.Key}\">");

                foreach (Type type in pair.Value)
                {
                    sb.AppendLine($"    <type fullname=\"{type.FullName}\" preserve=\"all\"/>");
                }

                sb.AppendLine("  </assembly>");
            }

            if (nativeModules.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("  <!-- ★ Unity 原生模块（本次扫代码自动补上）：整条模块的托管 wrapper 都保留。");
                sb.AppendLine("       不保不会报错，只会【编辑器正常、真机静默失效】—— 详见上面 ② 的说明。 -->");
                for (int i = 0; i < nativeModules.Count; i++)
                {
                    sb.AppendLine($"  <assembly fullname=\"{nativeModules[i]}\" preserve=\"all\"/>");
                }
            }

            sb.AppendLine("</linker>");
            return sb.ToString();
        }
    }
}
